// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxxiijablopmdarsgdcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54eGlpamFibG9wbWRhcnNnZGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzA2OTgsImV4cCI6MjA2NDk0NjY5OH0.pjtlepMXzHIYCCYCMxD3Q-WXprDIaF7NgNqODdSDQPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);